// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    var navRotator;
    return navRotator = setInterval(function() {
      var current;
      current = $('#pages li.active');
      if (current.next().length) {
        return current.next().trigger('click');
      } else {
        return $('#pages li:first-child').trigger('click');
      }
    }, 6000);
  });

  $('#pages li').live('click', function(e) {
    var marginLeft;
    e.preventDefault();
    marginLeft = -1 * parseInt($(this).attr('data-page')) * $('#artistNavWrapper').width();
    $('#artistNav').css('margin-left', marginLeft);
    $('#pages li.active').removeClass('active');
    return $(this).addClass('active');
  });

  $('div[data-href]').live('click', function(e) {
    $('iframe').attr('src', $(this).attr('data-href'));
    return $('body').attr('class', $(this).attr('data-class'));
  });

}).call(this);
